/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EventHandler;

/**
 *
 * @author Martin
 */
public enum MyEventType {
    ANY,
    SPELL_AURA_APPLIED,
    SPELL_CAST_SUCCESS,
    SPELL_AURA_REMOVED,
    SPELL_AURA_REFRESH,
    SPELL_AURA_APPLIED_DOSE,
    SPELL_SUMMON,
    SPELL_PERIODIC_ENERGIZE,
    SPELL_CAST_FAILED,
    SPELL_CAST_START,
    UNIT_DESTROYED,
    SPELL_CREATE,
    SPELL_AURA_REMOVED_DOSE,
    RANGE_DAMAGE,
    //RANGE_DAMAGE_LANDED,
    SPELL_DAMAGE,
    //SPELL_DAMAGE_LANDED,
    SWING_DAMAGE,
    //SWING_DAMAGE_LANDED,
    SPELL_EXTRA_ATTACKS,
    DAMAGE_SHIELD,
    SPELL_ENERGIZE,
    SPELL_PERIODIC_DAMAGE,
    SPELL_MISSED,
    SWING_MISSED,
    UNIT_DIED,
    SPELL_PERIODIC_HEAL,
    SPELL_AURA_BROKEN_SPELL,
    SPELL_HEAL,
    DAMAGE_SHIELD_MISSED,
    SPELL_DISPEL,
    SPELL_AURA_BROKEN,
    SPELL_ABSORBED,
    PARTY_KILL,
    SPELL_PERIODIC_DRAIN,
    RANGE_MISSED,
    SPELL_INSTAKILL,
    SPELL_PERIODIC_MISSED,
    SPELL_INTERRUPT,
    ENVIRONMENTAL_DAMAGE,
    COMBAT_LOG_VERSION,
    OTHER
}
